language: php

php:
  - 7.2
  - 7.3

before_script: 
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter 
- chmod +x ./cc-test-reporter 
- ./cc-test-reporter before-build

install: travis_retry composer install --no-interaction --prefer-dist --no-suggest

script: phpunit --coverage-clover=clover.xml

after_script: ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  
notifications:
  email: false
